#!/bin/sh
# @author Nicolas Thouvenin <touv@ouvaton.org>
# @version  $Id$
# @license http://opensource.org/licenses/gpl-license.php GNU Public License
# {{{ Header
SCRIPT_NAME=`basename $0`
function usage {

cat <<EOF

	SYNTAXE :
		${SCRIPT_NAME}  source destination

	DETAILS :
        Copie recursive d'un répertoire vers un autre
        Ce script permet de conserver les dates, les doits et les liens.
        RQ: source peut-être égalment un fichier régulier.


	EXEMPLES :
		$SCRIPT_NAME ~ /mnt/memory_card

EOF
    exit 0;
}
for argument in $*
do
    case $argument in
        -h | --help )
        usage
        ;;
        * )
        ;;
    esac
done
# }}}

if [[ ${#} -ne 2 ]]
then
    usage
fi

if [[ ! -d  $1 && ! -f $1 ]]
then
    usage
fi

if [[ ! -d  $2 ]]
then
    usage
fi

cp -Rdp $1 $2

# vim: fdm=marker
