#!/bin/sh
# @author Nicolas Thouvenin <touv@ouvaton.org>
# @version  $Id$
# @license http://opensource.org/licenses/gpl-license.php GNU Public License
# {{{ Header
SCRIPT_NAME=`basename $0`
function usage {

cat <<EOF

	SYNTAXE :
		${SCRIPT_NAME}  [CHEMIN]

	DETAILS :
        Rennome, dans [CHEMIN], tous les répertoirescvs en CVS         
        Rq: Si [CHEMIN] n'est pas préscié on utilise le répertoire commun


	EXEMPLES :
		$SCRIPT_NAME 
		$SCRIPT_NAME ~/mesimages

EOF
    exit 0;
}
for argument in $*
do
    case $argument in
        -h | --help )
        usage
        ;;
        * )
        ;;
    esac
done
# }}}

if [[ $# -eq 0 ]]
then
    CHEMIN="."
else 
    CHEMIN=$1    
fi

if [[ ! -d  ${CHEMIN} ]]
then
    usage
fi

savepath=`pwd`
cd $CHEMIN

for f in `find . -name "cvs"`
do
  if [ -d $f ]
      then
      d=`dirname $f`
      mv $f  $d/CVS
      echo "$f -> $d/CVS"
  fi

done



cd $savepath
# vim: fdm=marker
