#!/bin/sh
# @author Nicolas Thouvenin <touv@ouvaton.org>
# @license http://opensource.org/licenses/gpl-license.php GNU Public License
# {{{ Header
SCRIPT_NAME=`basename $0`
usage() {

cat <<EOF

	SYNTAXE :
		${SCRIPT_NAME} sujet tag

	DETAILS :
        Prise de notes en mode suivi d'activité

	EXEMPLES :
		$SCRIPT_NAME toto blague

EOF
    exit 0;
}
for argument in $*
do
    case $argument in
        -h | --help )
        usage
        ;;
        * )
        ;;
    esac
done
# }}}

if test ${#} -ne 2
then
    usage
fi

urlencode() {
    jq -rn --arg v "$1" '$v|@uri'
}

AAAA=`date +%Y`
MM=`date +%m`
JJ=`date +%d`
XX=$1
NAME=${AAAA}/${AAAA}${MM}${JJ}-SP-${XX}.md
FILE=$HOME/Boulot/Dossiers/${NAME}
NAME_ENCODED=$(urlencode "$NAME")
FILE_ENCODED=$(urlencode "$FILE")
VAULT=Dossiers
LOCATION=`dirname $FILE`
TAG1=$(printf '%s' "$XX" | tr '-' '/')
TAG2=$(printf '%s' "$2" | tr '-' '/')

mkdir -p $LOCATION

if [ ! -f "$FILE" ]; then
   cat <<EOF > ${FILE}
---
created: ${AAAA}-${MM}-${JJ}
type: "Suivi de projet"
project: ${TAG1}
tags: [${TAG2}]
---

# Jalons
- [ ] 
- [ ] 

# Journal

## le ${JJ} ${MM} ${AAAA}


EOF

else 
   cat <<EOF >> ${FILE}

## le ${JJ} ${MM} ${AAAA}

EOF

fi
xdg-open "obsidian://open?vault=${VAULT}&file=${NAME_ENCODED}"  2>/dev/null >/dev/null &

# vim: fdm=marker
