.TH treeview 1  "Lundi 22 décembre 2003" "" "TouvSH"
.SH NAME
treeview \- visualiser une arborescence de fichiers
.SH SYNOPSIS
.B treeview
[CHEMIN] 
.SH DESCRIPTION
Commande très simple permettant de sortir sur la sortie standard
une présentation visuel d'une arborescence de fichiers.
.PP
Si on ne précise pas de répertoire, c'est le répertoire courrant 
qui est utilisé.
.SH OPTIONS
.TP
[CHEMIN] : emplacement d'un répertoire à visualiser
.SH EXAMPLES
.TP
Visualiser son compte :
treeview ~
.TP
Visualiser le répertoire courrant :
treeview
.SH EXIT STATUS
treeview ne renvoit aucun code d'erreur.

.SH "PLUS d'INFORMATIONS"

.PP
touvtools web page : http://touv.ouvaton.org/documents/touvtools/

.PP
TOUV homepage : http://touv.ouvaton.org/

.SH AUTHOR
Touv aka Nicolas Thouvenin.
