#!/bin/sh
# @author Nicolas Thouvenin <touv@ouvaton.org>
# @version  $Id$
# @license http://opensource.org/licenses/gpl-license.php GNU Public License
# {{{ Header
SCRIPT_NAME=`basename $0`
function usage {

cat <<EOF

	SYNTAXE :
		${SCRIPT_NAME}  fichier.tar.gz

	DETAILS :
        Un décompresse et on extrait un fichier d'archive au format tar.gz


	EXEMPLES :
		$SCRIPT_NAME truc.tar.gz

EOF
    exit 0;
}
for argument in $*
do
    case $argument in
        -h | --help )
        usage
        ;;
        * )
        ;;
    esac
done
# }}}

if [[ ${#} -ne 1 ]]
then
    usage
fi

if [[ ! -f  $1 ]]
then
    usage
fi

gzip -dc $1 | tar xvf -


# vim: fdm=marker
